# permissions for end users to view friends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: friend-viewer-role
rules:
- apiGroups:
  - webapp.gytigyg.io
  resources:
  - friends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.gytigyg.io
  resources:
  - friends/status
  verbs:
  - get
